meta_product_name: "Pickalgo"
meta_title: "Devenez testeur de promos !"
meta_description: "Avec Pickalgo, décidez vous-même du prix des promos... et bénficiez-en avant tout le monde ! Grâce à vous nous définissons le meilleur prix pour que la promo soit bénéfique aux clients et au vendeur."
meta_image: "tags.jpg"                           # Une image dans votre dossier app/assets/images/
