meta_product_name: "Pickalgo"
meta_title: "Décidez du prix que vous êtes prêt à payer pour les produits qui vous plaisent"
meta_description: "Nous tentons de vous faire bénéficier d'un prix plus favorable que celui que vous nous avez proposé"
meta_image: "tags.jpg"                           # Une image dans votre dossier app/assets/images/              # indispensable pour les Twitter Cards
