meta_product_name: "Pickalgo"
meta_title: "Devenez testeur de promos !"
meta_description: "Décidez vous-même du prix que devrait adopter une promo et bénéficiez avant tout le monde des meilleures promos sur les produits qui vous plaisent."
meta_image: "tags.jpg"                           # Une image dans votre dossier app/assets/images/
